// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package controller

import (
	"example.com/sample-go-wire/src/api/user/repository"
	"example.com/sample-go-wire/src/api/user/service"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Wire(db *mongo.Database) *user {
	userRepository := repository.New(db)
	userService := service.New(userRepository)
	controllerUser := New(userService)
	return controllerUser
}
